<?php

return [
    'words' => [
        'BAKJE',
        'CAVIA',
        'DRUIF',
        'FIETS',
        'GILDE',
        'HAVIK',
        'JAREN',
        'KAARS',
        'LUCHT',
        'NACHT',
        'PIANO',
        'REGEN',
        'SAMEN',
        'TAFEL',
        'VLOER',
        'WAGEN',
        'ZEVEN',
        'AARDE',
        'BREED',
        'CHIPS',
        'DRAAD',
        'EIKEN',
        'GROEP',
        'HOBBY',
        'JASJE',
        'KRAAN',
        'LASER',
        'MEDIA',
        'NEVEN',
        'RUGBY',
        'VAREN',
    ],
];
